[package]
name = "copy_crab"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
thiserror = "1.0.61"
inquire = "0.7.5"
rfd = "0.14.1"
colored = "2.1.0"
strum = "0.26"
strum_macros = "0.26"
